# =============================================================================
# app.py — BaristaBot-style Agentic RAG  •  Streamlit Frontend
# =============================================================================
# Run:   streamlit run app.py
# =============================================================================

import os
import json
import time
import pathlib
import textwrap
from dotenv import load_dotenv

# ── Load .env BEFORE importing langchain/groq so vars are already set ─────────
load_dotenv()

# ── Required keys ─────────────────────────────────────────────────────────────
GROQ_API_KEY   = os.getenv("GROQ_API_KEY", "")
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY", "")

# ── Optional keys ─────────────────────────────────────────────────────────────
GOOGLE_API_KEY  = os.getenv("GOOGLE_API_KEY", "")
LANGCHAIN_API_KEY = os.getenv("LANGCHAIN_API_KEY", "")

# ── LangSmith tracing (enabled when LANGCHAIN_API_KEY is present) ─────────────
if LANGCHAIN_API_KEY:
    os.environ["LANGCHAIN_TRACING_V2"]  = "true"
    os.environ["LANGCHAIN_API_KEY"]     = LANGCHAIN_API_KEY
    os.environ["LANGCHAIN_ENDPOINT"]    = "https://api.smith.langchain.com"
    os.environ["LANGCHAIN_PROJECT"]     = os.getenv("LANGCHAIN_PROJECT", "agentic-rag")
else:
    os.environ["LANGCHAIN_TRACING_V2"] = "false"

# ── Push remaining keys into env so LangChain picks them up ───────────────────
if GROQ_API_KEY:
    os.environ["GROQ_API_KEY"] = GROQ_API_KEY
if TAVILY_API_KEY:
    os.environ["TAVILY_API_KEY"] = TAVILY_API_KEY
if GOOGLE_API_KEY:
    os.environ["GOOGLE_API_KEY"] = GOOGLE_API_KEY

# ── Streamlit ──────────────────────────────────────────────────────────────────
import streamlit as st

# ── Attempt to import the agent from the notebook-extracted module ─────────────
AGENT_AVAILABLE = False
agent_run = None
NOTEBOOK_PATH = pathlib.Path("agentic_rag.ipynb")

try:
    # Load notebook source for display
    if NOTEBOOK_PATH.exists():
        nb_text = NOTEBOOK_PATH.read_text(encoding="utf-8")
        nb_json = json.loads(nb_text)
    else:
        nb_json = None

    # Try importing the compiled agent module (generated by the notebook)
    import importlib, sys
    if pathlib.Path("agentic_rag_agent.py").exists():
        spec = importlib.util.spec_from_file_location("agentic_rag_agent",
                                                        "agentic_rag_agent.py")
        mod  = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        agent_run      = mod.agent_run       # expected public function
        AGENT_AVAILABLE = True
except Exception as exc:
    agent_run = None
    _import_error = str(exc)


# =============================================================================
# PAGE CONFIG & GLOBAL CSS
# =============================================================================
st.set_page_config(
    page_title="Agentic RAG",
    page_icon="🔍",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown("""
<style>
/* ── Fonts ──────────────────────────────────────────────── */
@import url('https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=DM+Mono:wght@400;500&family=DM+Sans:wght@300;400;500&display=swap');

html, body, [class*="css"] { font-family: 'DM Sans', sans-serif; }
h1, h2, h3 { font-family: 'DM Serif Display', serif; letter-spacing: -0.5px; }
code, pre   { font-family: 'DM Mono', monospace !important; }

/* ── Root palette ────────────────────────────────────────── */
:root {
    --bg:       #0d0f14;
    --surface:  #13161e;
    --border:   #232635;
    --accent:   #7c6af7;
    --accent2:  #4fc3f7;
    --text:     #e2e4f0;
    --muted:    #6b7280;
    --success:  #34d399;
    --warn:     #fbbf24;
    --danger:   #f87171;
}

/* ── Base ────────────────────────────────────────────────── */
.stApp { background: var(--bg); color: var(--text); }

/* ── Sidebar ─────────────────────────────────────────────── */
section[data-testid="stSidebar"] {
    background: var(--surface);
    border-right: 1px solid var(--border);
}

/* ── Text input / text area ──────────────────────────────── */
.stTextArea textarea, .stTextInput input {
    background: var(--surface) !important;
    border: 1px solid var(--border) !important;
    color: var(--text) !important;
    border-radius: 8px !important;
    font-family: 'DM Sans', sans-serif !important;
}
.stTextArea textarea:focus, .stTextInput input:focus {
    border-color: var(--accent) !important;
    box-shadow: 0 0 0 2px rgba(124,106,247,.25) !important;
}

/* ── Buttons ─────────────────────────────────────────────── */
.stButton > button {
    background: var(--accent);
    color: #fff;
    border: none;
    border-radius: 8px;
    font-family: 'DM Mono', monospace;
    font-size: .85rem;
    letter-spacing: .04em;
    padding: .55rem 1.4rem;
    transition: background .2s, transform .1s;
}
.stButton > button:hover  { background: #6355d4; transform: translateY(-1px); }
.stButton > button:active { transform: translateY(0); }

/* ── Answer card ─────────────────────────────────────────── */
.answer-card {
    background: var(--surface);
    border: 1px solid var(--border);
    border-left: 4px solid var(--accent);
    border-radius: 10px;
    padding: 1.25rem 1.5rem;
    margin-top: 1rem;
    line-height: 1.7;
}
.source-tag {
    display: inline-block;
    background: rgba(124,106,247,.15);
    color: var(--accent);
    border: 1px solid rgba(124,106,247,.3);
    border-radius: 4px;
    font-family: 'DM Mono', monospace;
    font-size: .72rem;
    padding: .1rem .45rem;
    margin: .15rem .15rem 0 0;
    text-decoration: none;
}
.step-row {
    display: flex; align-items: flex-start; gap: .7rem;
    padding: .4rem 0; border-bottom: 1px solid var(--border);
    font-size: .85rem;
}
.step-icon { font-size: 1rem; min-width: 1.4rem; }
.step-text  { color: var(--muted); }
.chip {
    display: inline-block; padding: .15rem .55rem;
    border-radius: 999px; font-size: .72rem;
    font-family: 'DM Mono', monospace;
}
.chip-ok   { background: rgba(52,211,153,.15); color: var(--success); }
.chip-warn { background: rgba(251,191,36,.15);  color: var(--warn); }
.chip-err  { background: rgba(248,113,113,.15); color: var(--danger); }
</style>
""", unsafe_allow_html=True)


# =============================================================================
# SIDEBAR — config & status
# =============================================================================
with st.sidebar:
    st.markdown("## ⚙️ Configuration")

    st.markdown("**API Key Status**")
    def key_badge(label, val):
        ok = bool(val)
        cls = "chip-ok" if ok else "chip-err"
        txt = "✓ set" if ok else "✗ missing"
        st.markdown(f'<span class="chip {cls}">{label}: {txt}</span>',
                    unsafe_allow_html=True)
    key_badge("GROQ",      GROQ_API_KEY)
    key_badge("TAVILY",    TAVILY_API_KEY)
    key_badge("GOOGLE",    GOOGLE_API_KEY)
    key_badge("LANGSMITH", LANGCHAIN_API_KEY)

    st.divider()
    st.markdown("**Agent Settings**")
    model_name = st.selectbox("Groq model",
        ["llama-3.3-70b-versatile", "llama3-8b-8192", "mixtral-8x7b-32768"],
        index=0)
    max_iterations = st.slider("Max agent iterations", 1, 10, 5)
    use_web_search = st.toggle("Enable web search (Tavily)", value=True)

    st.divider()
    if LANGCHAIN_API_KEY:
        st.markdown('<span class="chip chip-ok">LangSmith tracing ON</span>',
                    unsafe_allow_html=True)
    else:
        st.markdown('<span class="chip chip-warn">LangSmith tracing OFF</span>',
                    unsafe_allow_html=True)

    st.divider()
    st.markdown("**Quick links**")
    st.markdown("- [LangSmith](https://smith.langchain.com)")
    st.markdown("- [Groq Console](https://console.groq.com)")
    st.markdown("- [Tavily](https://tavily.com)")


# =============================================================================
# MAIN CONTENT
# =============================================================================
st.markdown("# 🔍 Agentic RAG")
st.markdown(
    '<p style="color:var(--muted);font-size:.95rem;margin-top:-.5rem;">'
    'Retrieval-augmented generation · powered by Groq + Tavily + LangGraph'
    '</p>',
    unsafe_allow_html=True,
)

# ── Session state ─────────────────────────────────────────────────────────────
if "history" not in st.session_state:
    st.session_state.history = []   # list of {query, answer, sources, steps, elapsed}

# ── Query input ───────────────────────────────────────────────────────────────
query = st.text_area(
    "Ask anything — the agent will retrieve, reason, and synthesize an answer:",
    height=90,
    placeholder="e.g. What are the latest advances in multimodal LLMs?",
    key="query_input",
)

col_submit, col_clear, col_spacer = st.columns([1, 1, 6])
with col_submit:
    submitted = st.button("🚀 Submit", use_container_width=True)
with col_clear:
    if st.button("🗑 Clear", use_container_width=True):
        st.session_state.history = []
        st.rerun()

# =============================================================================
# AGENT CALL (or simulation)
# =============================================================================
if submitted and query.strip():
    with st.spinner("Agent is thinking…"):
        t0 = time.time()

        if AGENT_AVAILABLE and agent_run:
            # ── Real agent call ────────────────────────────────────────────
            try:
                result = agent_run(
                    query=query,
                    model_name=model_name,
                    max_iterations=max_iterations,
                    use_web_search=use_web_search,
                )
                answer  = result.get("answer", "No answer returned.")
                sources = result.get("sources", [])
                steps   = result.get("steps",  [])
            except Exception as exc:
                answer  = f"⚠️ Agent error: {exc}"
                sources = []
                steps   = [{"icon": "❌", "text": str(exc)}]

        else:
            # ── Simulated response (notebook not yet compiled) ─────────────
            time.sleep(1.2)   # simulate latency
            answer = textwrap.dedent(f"""
                **[Simulated answer — connect the real agent in `agentic_rag.ipynb`]**

                Your query was: *"{query}"*

                The agentic RAG pipeline would:
                1. Embed the query and search the vector store (ChromaDB / FAISS).
                2. Call Tavily web search if the retriever score is below threshold.
                3. Pass retrieved context + the original query to the Groq LLM
                   (`{model_name}`) for synthesis.
                4. Return a grounded answer with source attribution.

                Once you export `agent_run()` from the notebook into
                `agentic_rag_agent.py`, this placeholder disappears automatically.
            """).strip()
            sources = [
                {"title": "ChromaDB docs", "url": "https://docs.trychroma.com"},
                {"title": "Tavily API",     "url": "https://docs.tavily.com"},
                {"title": "Groq Cloud",     "url": "https://console.groq.com/docs"},
            ]
            steps = [
                {"icon": "🔎", "text": "Query embedded with HuggingFace sentence-transformer"},
                {"icon": "📚", "text": "Vector store searched — top-3 chunks retrieved"},
                {"icon": "🌐", "text": "Tavily web search called (score below threshold)"},
                {"icon": "🧠", "text": f"Groq `{model_name}` synthesised answer"},
                {"icon": "✅", "text": "Sources attributed"},
            ]

        elapsed = time.time() - t0

    st.session_state.history.insert(0, {
        "query":   query,
        "answer":  answer,
        "sources": sources,
        "steps":   steps,
        "elapsed": elapsed,
    })

# =============================================================================
# DISPLAY HISTORY
# =============================================================================
for i, item in enumerate(st.session_state.history):
    with st.container():
        st.markdown(f"**Q:** {item['query']}")

        # Answer card
        st.markdown(
            f'<div class="answer-card">{item["answer"]}</div>',
            unsafe_allow_html=True,
        )

        # Sources
        if item["sources"]:
            src_html = " ".join(
                f'<a class="source-tag" href="{s.get("url","#")}" target="_blank">'
                f'🔗 {s.get("title", s.get("url","source"))}</a>'
                for s in item["sources"]
            )
            st.markdown(src_html, unsafe_allow_html=True)

        # Reasoning steps (collapsible)
        if item["steps"]:
            with st.expander(f"🔬 Reasoning trace  •  {item['elapsed']:.1f}s", expanded=(i==0)):
                for step in item["steps"]:
                    icon = step.get("icon", "•")
                    text = step.get("text", "")
                    st.markdown(
                        f'<div class="step-row">'
                        f'<span class="step-icon">{icon}</span>'
                        f'<span class="step-text">{text}</span>'
                        f'</div>',
                        unsafe_allow_html=True,
                    )

        st.divider()

# =============================================================================
# NOTEBOOK VIEWER (optional, bottom of page)
# =============================================================================
if NOTEBOOK_PATH.exists():
    with st.expander("📓 View agentic_rag.ipynb source", expanded=False):
        try:
            nb = json.loads(NOTEBOOK_PATH.read_text())
            for cell in nb.get("cells", []):
                src = "".join(cell.get("source", []))
                if cell["cell_type"] == "markdown":
                    st.markdown(src)
                elif cell["cell_type"] == "code":
                    st.code(src, language="python")
        except Exception as exc:
            st.warning(f"Could not parse notebook: {exc}")
else:
    st.info("ℹ️  `agentic_rag.ipynb` not found — place it next to `app.py` to enable the viewer.")
